image: eclipse-temurin:17
stages:
    - build

build:
    stage: build
    script:
        - export NODE_OPTIONS=--openssl-legacy-provider
        - './mvnw deploy -s .gitlab/ci_settings.xml'
    only:
        - tags
    except:
        - branches
